spring:
  output:
    ansi:
      enabled: always
  profiles:
    active:
      - sqlite

java:
  version: 1.8
---
spring:
  profiles: real-1
  datasource:
    url: jdbc:mysql://localhost:3307/dashboard
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
---
spring:
  profiles: dev-2
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://mysql:3306/dashboard
    username: dashboard_user
    password: dashboard_pass
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: h2-persistance
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file:./data/app_db2;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8083
---
spring:
  profiles: dev-h2-persistance
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:file:./data/app_db3;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles:
    - sqlite
  datasource:
    url: jdbc:sqlite:./data/march.sqlite3
    username: sa
    password: sa
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: demo.dublin.dashboard.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: 'update'
      generate_statistics: true

logging:
  level:
    org:
      hibernate: debug
---
spring:
  profiles:
    - sqlite-dev
  datasource:
    url: jdbc:sqlite:./data/dev-db.sqlite3
    username: sa
    password: sa
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: demo.dublin.dashboard.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: 'update'
      generate_statistics: true

logging:
  level:
    org:
      hibernate: debug